title: "Ye-Fang Wong | Senior Software Developer"
email: "yefang.wong@gmail.com"
description: "Senior Software Developer specializing in Responsible AI Guardrails and Mission-Critical Backend Infrastructures."
baseurl: ""
url: "https://yefangwong.github.io"
permalink: /posts/:year-:month-:day-:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
